version: "3.9"

services:
  golang-server:
    container_name: golang-server
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - LOG_TYPE=USER_FRIENDLY
      - ROOT_PATH=/app
    ports:
      - "54528:54528"
