version: "3.9"

services:
  golang-server:
    container_name: golang-server
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - LOG_TYPE=USER_FRIENDLY
      - ROOT_PATH=/app
      - PORT=54528
      - ENV=development
      - DATABASE_URL=postgresql://postgres:123456789@postgres:5432/custom_holiday?sslmode=disable
      - MIGRATION_URL=file:///app/db/migration
    ports:
      - "54528:54528"
    volumes:
      - .:/app
    networks:
      - custom_holiday_network

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5456:5432
    volumes:
      - postgresql-data:/var/lib/postgresql:Z
    env_file:
      - .env
    networks:
      - custom_holiday_network

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8989:80"
    networks:
      - custom_holiday_network

networks:
  custom_holiday_network:


volumes:
  postgresql-data:
