version: "3.9"

services:
  golang-server:
    container_name: golang-server
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "54528:54528"
    volumes:
      - .:/app